OppenDC/OppenDC/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views
#include for import app/urls.py (in future)
from app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.loginPage, name='login'),
    path('OppenDC/', views.home, name='OppenDC'),
    path('admin/', admin.site.urls),
    path('OppenDC/Deploy/', views.deploy, name='Deploy'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OppenDC/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.index, name='index'),
]

OppenDC/app/models.py
from django.db import models
from django.core.validators import URLValidator

# Create your models here.

class Source(models.Model):
    STATUS = (
        (0, 'ERROR'),
        (1, 'PASSED'),
    )
    code = models.CharField(max_length=20, unique=True, db_index=True)
    name = models.CharField(max_length=50)
    gitrepo = models.CharField(max_length=100, null=True)
    lastcontrol = models.DateTimeField(null=True)
    status = models.BooleanField(choices=STATUS)
    build_version = models.CharField(max_length=20, null=True)
    internal_teamcity_build = models.IntegerField(null=True)
    on_revision = models.BooleanField()

    def __str__(self):
        return self.name

class Client(models.Model):
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=50)

class Server(models.Model):
    SERVER_TYPES = (
        ('CLIENT','CLIENT'),
        ('OWN','OWN'),
        ('OTHER','OTHER'),
    )
    server_code = models.CharField(max_length=20, unique=True, db_index=True)
    server_type = models.CharField(max_length=10, choices=SERVER_TYPES)
    server_name = models.CharField(max_length=50)
    url = models.CharField(max_length=100, validators=[URLValidator()])

    def __str__(self):
        return self.server_name

class Target(models.Model):
    TARGET_TYPE = (
        (0, 'QA'),
        (1, 'Canary'),
        (2, 'Normal'),
    )
    client_code = models.ForeignKey(Client, on_delete=models.CASCADE)
    server_code = models.ForeignKey(Server, on_delete=models.CASCADE)
    target_name = models.CharField(max_length=50, db_index=True)
    sources_group = models.ManyToManyField(Source, through='SourcesTargets')
    url_target = models.CharField(max_length=100, validators=[URLValidator()])
    target_type = models.IntegerField(choices=TARGET_TYPE, default=2)
    username = models.CharField(max_length=50, null=True)
    password = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.target_name

class SourcesTargets(models.Model):
    target_id = models.ForeignKey(Target, on_delete=models.CASCADE)
    source_id = models.ForeignKey(Source, on_delete=models.CASCADE)
    last_update = models.DateTimeField(auto_now=True)
    source_build_version = models.CharField(max_length=20, null=True)
    
    def __str__(self):
        return str(self.target_id) +':'+ str(self.source_id)  +':'+ str(self.last_update)  +':'+ str(self.source_build_version)

class Update(models.Model):
    UPDATE_STATUS = (
        (0, 'QA'),
        (1, 'Canary'),
        (2, 'Deploy'),
    )
    source_code = models.CharField(max_length=20, db_index=True)
    create_datetime = models.DateTimeField()
    source_build_version = models.CharField(max_length=20)
    source_build = models.FileField(upload_to='builds/%Y/')
    stage = models.IntegerField(choices=UPDATE_STATUS, default=0)
    closed = models.BooleanField()
    next_stage_datetime_set = models.DateTimeField()
    internal_teamcity_build = models.IntegerField(default=0)
    scriptdir_name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.source_code +' : '+ self.source_build_version  +' : '+ str(self.create_datetime)  +' : '+ str(self.stage)


class DeployHistory(models.Model):
    HISTORY_STATUS = (
        (0, 'FAIL'),
        (1, 'SUCCESS'),
        (2, 'UNKNOWN'),
    )
    date = models.DateField()
    time = models.TimeField()
    target_id = models.ForeignKey(Target, on_delete=models.CASCADE)
    status = models.IntegerField(choices=HISTORY_STATUS)

    def __str__(self):
        return str(self.date)  +':'+ str(self.time)  +':'+ str(self.target_id)

OppenDC/app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpRequest
from django.template import RequestContext
from app.models import Source, Update
from app import teamcityconnect, notifications
from datetime import datetime, timedelta

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('OppenDC')
    return render(request, 'app/index.html')

def loginPage(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['inputUsername']
            password = request.POST['inputPassword']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request,user)
                # context = {'username': user.username }
                return HttpResponseRedirect(reverse('OppenDC'))
            else:   
                return render(request, 'app/login.html', {'retry':True})
        else: return render(request, 'app/login.html')
    else: return HttpResponseRedirect(reverse('OppenDC'))

@login_required()
def home(request):
    user = request.user
    last_name = user.last_name
    first_name = user.first_name
    if len(first_name) > 0 and len(last_name) > 0:
        name_to_show = user.last_name +', '+ user.first_name
    else:
        name_to_show = user.username
    request.session['name_to_show'] = name_to_show
    sources = Source.objects.all()
    if 'refresh_sources' in request.POST:
        teamcityconnect.takeSourcesStatus(sources)
    context = {'sources': sources } #sources[0].name
    return render(request, 'app/home.html', context)

@login_required()
def deploy(request):
    if request.method == 'POST':
        if 'candidate' in request.POST:
            source_candidate = Source.objects.get(id=request.POST['candidate'])
            record = Update(source_code=source_candidate.code)
            record.create_datetime = datetime.now()
            record.source_build_version = source_candidate.build_version
            record.stage = 0 #QA UPDATE_STATOS, see models.
            record.closed = False
            record.next_stage_datetime_set = datetime.now() + timedelta(days=1)
            record.internal_teamcity_build = source_candidate.internal_teamcity_build
            file_name = str(source_candidate.code)+"V"+str(source_candidate.build_version)+".zip"
            record.source_build.save(file_name, teamcityconnect.takeSourceBuild(record))
            record.save()
            print("ENTRE EN CANDIDATO")
        if 'deploy' in request.POST:
            print('ENTRE EN DEPLOY')
            update = Update.objects.get(id=request.POST['deploy'])
            notifications.targetsForNotify(update)

    deploys = Update.objects.all()
    context = {'deploys': deploys }
    return render(request, 'app/deploy.html', context)

OppenDC/app/templates/app/deploy.html
{% extends "app/home.html" %}

{% block content %}
<div class="col-sm-8">
    <h3 class="mt-1">Deploys</h3>
    {% for deplo in deploys %}
    <form action="{% url 'Deploy' %}" method="post">
        {% csrf_token %}
    <div class="card">
        <div class="card-body text-center">
            <div class="row">
                <div class="col-sm-4">
                    <h5 class="card-title">  {{ deplo.source_code }} - {{ deplo.source_build_version }}</h5>
                    <p class="card-text">Creación: {{ deplo.create_datetime }}</p>
                    <p class="card-text">Proximo Estado</p>
                </div>
                <div class="col-sm-4">
                    <row>
                        <select class="custom-select">
                            <option selected name="to_deploy">{{ deplo.get_stage_display }}</option>
                            {% if deplo.stage == 0 %}
                                <option value="1">Canary</option>
                                <option value="2">Deploy</option>
                            {% elif deplo.stage == 1 %}
                                <option value="0">QA</option>
                                <option value="2">Deploy</option>
                            {% elif deplo.stage == 2 %}
                                <option value="1">Canary</option>
                                <option value="2">Deploy</option>
                            {% endif %}
                        </select>
                    </row>
                    <row>
                        <a href=" {{ deplo.source_build.url }} " class="badge badge-info">Descargar Build</a>
                        <a href="#" class="badge badge-secundary">Detalles</a>
                    </row>
                </div>
                <div class="col-sm-4">
                    <div class="alert alert-secondary" role="alert">
                            This is a secondary alert—check it out!
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="container-fluid">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                Deploy
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Confirmar Deploy</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ¿Desea confirmar el Deploy de {{ deplo.source_code }} para los tipos {{ deplo.get_stage_display }}?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                      <button class="btn btn-primary" type="submit" name="deploy" value= "{{ deplo.id }}" >Deploy</button>
                    </div>
                  </div>
                </div>
              </div>
    </form>
    {% endfor %}
</div>
{% endblock %}


      

OppenDC/app/templates/app/home.html
{% extends "app/index.html" %}

{% block navigationBar %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark  fixed-top" style="background-color: #062491;">
    <div class="container">
      <a class="navbar-brand" href="#">
            <img class="img-fluid" width="100" src="{% static 'app/images/oppen.png' %}" alt=""/> Deployment Control
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">My Profile
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link"> {{ request.session.name_to_show }} </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block sidebar %}
{% load static %}
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'OppenDC' %}"><img src="{% static 'app/icons/home-3x.png' %}" class="img-fluid img-thumbnail" alt="Dashboard"  %>
                Sources
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <a class="nav-link active" href="{% url 'Deploy' %}"><img src="{% static 'app/icons/share-3x.png' %}" class="img-fluid img-thumbnail" alt="Deploys"  %>
                Deploys
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <a class="nav-link active" href="#"><img src="{% static 'app/icons/target-3x.png' %}" class="img-fluid img-thumbnail" alt="Targets"  %>
                Targets
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <a class="nav-link active" href="#"><img src="{% static 'app/icons/clock-3x.png' %}" class="img-fluid img-thumbnail" alt="History"  %>
                History
              </a>
            </li>
            

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>New Data</span>
            <a class="d-flex align-items-center text-muted" href="/admin">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <a class="nav-link active" href="#"><img src="{% static 'app/icons/cog-3x.png' %}" class="img-fluid img-thumbnail" alt="Settings"  %>
                Settings
              </a>
            </li>
          </ul>
        </div>
      </nav>
{% endblock %}

{% block content %}
        <div class="col">
            <h3 class="mt-1">Listado de Fuentes</h3>
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Version del Build</th>
                        <th scope="col">Último Control</th>
                        <th scope="col">Estado</th>
                    </tr>
                    </thead>
                    <tbody>
                    <form action="{% url 'Deploy' %}" method="post">
                    {% csrf_token %}
                    {% for source in sources %}
                    <tr>
                        <th scope="row"> {{ source.id }} </th>
                        <td>{{ source.name }}</td>
                        <td>{{ source.build_version }}</td>
                        <td>{{ source.lastcontrol }}</td>
                        {% if source.status %}
                        <td> Correcto </td>
                        {% else %}
                        <td> Con Error </td>
                        {% endif %}
                        <td>
                            <button class="btn btn-secondary" type="submit" name="candidate" value= {{ source.id }} >
                                Candidato
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                    </form>
                    </tbody>
                </table>
            <form action="{% url 'OppenDC' %}" method="post">
                {% csrf_token %}
            <button class="btn btn-primary btn-block" type="submit" name="refresh_sources" value="True" >Actualizar</button>
            </form>
        </div>
{% endblock %}

OppenDC/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OppenDC</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link href="{% static 'app/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>
  </head>

  <body>
    <!-- Navigation -->
    {% block navigationBar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
                <img class="img-fluid" width="100" src="{% static 'app/images/oppen.png' %}" alt=""> Deployment Control</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}

    <!-- Page Content -->
    <div class="container-fluid">
        <div class="row">
    {% block sidebar %}
    {% endblock %}
    {% block content %}
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="mt-5">Oppen Deployment Control</h1>
          <p class="lead">Custom Deployment Platform for Oppen Software</p>
          <p>Technologies</p>
          <ul class="list-unstyled">
            <li>Python 3.6.4</li>
            <li>Django 2.0.2</li>
            <li>Bootstrap 4.0.0</li>
            <li>jQuery 3.3.0</li>
            <li>MySql Server 5.7</li>
          </ul>
          <a class="nav-link" href="{% url 'login' %}">Please log in</a>
          <p>If you don't have an account, contact with the admin</p>
        </div>
      </div>
    </div>
    {% endblock %}
        </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    {% block scripts %}
    <script src="{% static 'app/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'app/js/bootstrap.bundle.min.js' %}"></script>
    {% endblock %}
  </body>
</html>

OppenDC/app/templates/app/login.html
{% extends "app/index.html" %}
{% block content %}
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Oppen: LogIn</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'app/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'app/css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <form action="{% url 'login' %}" method="post" class="form-signin">
                        {% csrf_token %}
                        <img class="img-fluid" src="{% static 'app/images/oppen.png' %}" alt="">
                        <h1 class="h3 mb-3 font-weight-normal">Deployment Control</h1>
                        {% if retry == True %}<div class="alert alert-warning" role="alert">
                                Username or Password Invalid</div>{% endif %}
                        <label for="inputUsername" class="sr-only">Username</label>
                        <input type="text" id="inputUsername" name="inputUsername" class="form-control" placeholder="Username" required autofocus>
                        <label for="inputPassword" class="sr-only">Password</label>
                        <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Password" required>
                        <div class="checkbox mb-3">
                            <label>
                            <input type="checkbox" value="remember-me"> Remember me
                            </label>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                        <p class="mt-5 mb-3 text-muted">&copy; M.Colombo - Oppen 2018</p>
                    </form>
                </div>
            </div>
        </div>
  </body>
</html>
{% endblock %}